#!/bin/bash
# See AUTHORS for a list of contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General
# Public License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

DIR=/tmp/kaleidos/
#Compruebo que la carpeta no este creada
# El entrecomillado de $DIR es importante
# Tambien es importante el espacion entre el if y el corchete
if [ ! -d "$DIR" ]; then
  mkdir $DIR
  ln -s $DIR ~/kaleidos
fi

#Compruebo que se alla ingresado una URL
if [ ! $1 ]; then
  echo 'Ingrese una url para descargar'
  read URL
else
  URL=$1
fi

#Compruebo que la variable no exista
if [ ! $2 ]; then
  echo 'Como se llamara el archivo ?'
  read NAME
else
  NAME=$2
fi

wget -q -N $URL -O $DIR$NAME.jpg
kaleidoscopic -m image -o 0 $DIR$NAME.jpg $DIR$NAME.00.jpg
kaleidoscopic -m image -o 90 $DIR$NAME.jpg $DIR$NAME.01.jpg
kaleidoscopic -m image -o 180 $DIR$NAME.jpg $DIR$NAME.02.jpg
kaleidoscopic -m image -o 270 $DIR$NAME.jpg $DIR$NAME.03.jpg
kaleidoscopic -m image -o 270 -i $DIR$NAME.jpg $DIR$NAME.04.jpg
kaleidoscopic -m image -o 180 -i $DIR$NAME.jpg $DIR$NAME.05.jpg
kaleidoscopic -m image -o 90 -i $DIR$NAME.jpg $DIR$NAME.06.jpg
kaleidoscopic -m image -o 0 -i $DIR$NAME.jpg $DIR$NAME.07.jpg

kaleidoscopic -m image -o 90 -i $DIR$NAME.00.jpg $DIR$NAME.08.jpg
kaleidoscopic -m image -o 180 -i $DIR$NAME.01.jpg $DIR$NAME.09.jpg
kaleidoscopic -m image -o 0 $DIR$NAME.04.jpg $DIR$NAME.10.jpg

echo 'Caleidoscopio acaleidoscopeado terminado...'
echo 'Recordar mover las imagenes que se deseen guardar a otro directorio... estas son temporales'

ristretto $DIR$NAME.jpg &

exit 0
